### ISSUE TITLE
5th Gen time finder randomly crashes

### ISSUE THREAD

**Issue by shinymarill23** [Bambo-Rambo/RNGReporter#5]
Sometimes when I select certain months in the 5th gen time finder the search crashes. I thought it was because I was selecting too many months at once, but it keeps happening even with 1 month. Here is is the entry in the event log:

```
Application: RNGReporter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.DateTime.DateToTicks(Int32, Int32, Int32)
   at RNGReporter.TimeFinder5th.GeneratePickupJob(UInt32, System.Collections.Generic.List`1<Int32>, Int32, Int32, RNGReporter.Objects.Profile, Int32)
   at RNGReporter.TimeFinder5th+<>c__DisplayClass152_1.<buttonPickupSearch_Click>b__2()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Bambo-Rambo** [comment]
Can you try lowering the number of threads you are using from the main window?

**Comment by shinymarill23** [comment]
I don't know how to do that (lowering the threads). But, I have found out that if I only search on months that have 31 days, the issue doesn't happen at all. As soon as I include a month with less than 31 days (e.g. february) then the exception happens. That tracks with the call stack in the exception:
 System.ArgumentOutOfRangeException
   **at System.DateTime.DateToTicks(Int32, Int32, Int32)**
   at RNGReporter.TimeFinder5th.GeneratePickupJob(UInt32, System.Collections.Generic.List`1<Int32>, Int32, Int32, 
   ... etc
